// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001130445_AddCustomersTable")]
    partial class AddCustomersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo, chocolate"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước có ga, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Nước suối & Nước đóng chai",
                            Description = "Nước lọc, nước khoáng, nước tinh khiết đóng chai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sữa & Đồ uống dinh dưỡng",
                            Description = "Sữa tươi, sữa hộp, sữa chua, thức uống dinh dưỡng"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Mì & Thực phẩm ăn liền",
                            Description = "Mì gói, mì ly, cháo ăn liền, phở ăn liền"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Thực phẩm đóng hộp",
                            Description = "Cá hộp, thịt hộp, pate, rau củ đóng hộp"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ ăn nhanh",
                            Description = "Xúc xích, sandwich, hamburger, cơm hộp"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cà phê & Trà",
                            Description = "Cà phê hòa tan, cà phê lon, trà túi lọc"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Gia vị & Thực phẩm khô",
                            Description = "Nước mắm, nước tương, đường, muối, gia vị"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ dùng cá nhân",
                            Description = "Bàn chải, kem đánh răng, dầu gội, sữa tắm"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Chăm sóc sức khỏe",
                            Description = "Khẩu trang, băng cá nhân, nước rửa tay"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ dùng gia đình",
                            Description = "Khăn giấy, túi rác, nước rửa chén"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút, vở, giấy, dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Đông lạnh",
                            Description = "Kem, thực phẩm đông lạnh, xúc xích"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Trái cây & Thực phẩm tươi",
                            Description = "Trái cây, rau củ và thực phẩm tươi"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901234567",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0912345678",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Quận 7, TP. Hồ Chí Minh",
                            CustomerName = "Lê Minh Cường",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0923456789",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0934567890",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Quận Bình Thạnh, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Minh Đức",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0945678901",
                            RewardPoints = 800
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Quận Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Võ Thị Hạnh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0956789012",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Quốc Huy",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0967890123",
                            RewardPoints = 420
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Ngọc Lan",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0978901234",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Quận 5, TP. Hồ Chí Minh",
                            CustomerName = "Phan Thanh Long",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0989012345",
                            RewardPoints = 260
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Quận 11, TP. Hồ Chí Minh",
                            CustomerName = "Ngô Thị Mai",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0990123456",
                            RewardPoints = 620
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Quận Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Văn Nam",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0881234567",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Quận 6, TP. Hồ Chí Minh",
                            CustomerName = "Vũ Thị Oanh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0872345678",
                            RewardPoints = 290
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Quận Bình Tân, TP. Hồ Chí Minh",
                            CustomerName = "Đinh Minh Phúc",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0863456789",
                            RewardPoints = 950
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Quận Tân Phú, TP. Hồ Chí Minh",
                            CustomerName = "Mai Thị Quỳnh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0854567890",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Quận 12, TP. Hồ Chí Minh",
                            CustomerName = "Trương Hoàng Sơn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0845678901",
                            RewardPoints = 45
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893850001001",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Bánh Oreo Chocolate",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893850001002",
                            CategoryId = 1,
                            Price = 15000m,
                            ProductName = "Snack khoai tây Lay's",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893850001003",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Kẹo dẻo Haribo",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893850002001",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Coca Cola 330ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893850002002",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Pepsi 330ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893850002003",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Sting Dâu 330ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893850003001",
                            CategoryId = 3,
                            Price = 6000m,
                            ProductName = "Aquafina 500ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893850003002",
                            CategoryId = 3,
                            Price = 6000m,
                            ProductName = "Lavie 500ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893850003003",
                            CategoryId = 3,
                            Price = 6000m,
                            ProductName = "Dasani 500ml",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893850004001",
                            CategoryId = 4,
                            Price = 35000m,
                            ProductName = "Vinamilk Sữa tươi",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893850004002",
                            CategoryId = 4,
                            Price = 36000m,
                            ProductName = "TH True Milk",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893850004003",
                            CategoryId = 4,
                            Price = 25000m,
                            ProductName = "Yakult",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893850005001",
                            CategoryId = 5,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo Tôm Chua Cay",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893850005002",
                            CategoryId = 5,
                            Price = 12000m,
                            ProductName = "Mì Omachi",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893850005003",
                            CategoryId = 5,
                            Price = 10000m,
                            ProductName = "Cháo ăn liền Vifon",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "893850006001",
                            CategoryId = 6,
                            Price = 28000m,
                            ProductName = "Cá hộp 3 Cô Gái",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "893850006002",
                            CategoryId = 6,
                            Price = 22000m,
                            ProductName = "Pate gan hộp",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "893850006003",
                            CategoryId = 6,
                            Price = 18000m,
                            ProductName = "Đậu Hà Lan đóng hộp",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "893850007001",
                            CategoryId = 7,
                            Price = 10000m,
                            ProductName = "Xúc xích CP",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "893850007002",
                            CategoryId = 7,
                            Price = 25000m,
                            ProductName = "Sandwich thịt nguội",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "893850007003",
                            CategoryId = 7,
                            Price = 30000m,
                            ProductName = "Hamburger bò",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "893850008001",
                            CategoryId = 8,
                            Price = 30000m,
                            ProductName = "Cà phê hòa tan G7",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "893850008002",
                            CategoryId = 8,
                            Price = 12000m,
                            ProductName = "Cà phê lon Birdy",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "893850008003",
                            CategoryId = 8,
                            Price = 10000m,
                            ProductName = "Trà xanh C2",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "893850009001",
                            CategoryId = 9,
                            Price = 35000m,
                            ProductName = "Nước mắm Nam Ngư",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "893850009002",
                            CategoryId = 9,
                            Price = 18000m,
                            ProductName = "Nước tương Chinsu",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "893850009003",
                            CategoryId = 9,
                            Price = 22000m,
                            ProductName = "Đường tinh luyện",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "893850010001",
                            CategoryId = 10,
                            Price = 30000m,
                            ProductName = "Kem đánh răng P/S",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "893850010002",
                            CategoryId = 10,
                            Price = 45000m,
                            ProductName = "Dầu gội Sunsilk",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "893850010003",
                            CategoryId = 10,
                            Price = 50000m,
                            ProductName = "Sữa tắm Lifebuoy",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 31,
                            Barcode = "893850011001",
                            CategoryId = 11,
                            Price = 25000m,
                            ProductName = "Khẩu trang y tế",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 32,
                            Barcode = "893850011002",
                            CategoryId = 11,
                            Price = 15000m,
                            ProductName = "Băng cá nhân",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 33,
                            Barcode = "893850011003",
                            CategoryId = 11,
                            Price = 45000m,
                            ProductName = "Nước rửa tay Lifebuoy",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 34,
                            Barcode = "893850012001",
                            CategoryId = 12,
                            Price = 25000m,
                            ProductName = "Khăn giấy Pulppy",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 35,
                            Barcode = "893850012002",
                            CategoryId = 12,
                            Price = 35000m,
                            ProductName = "Nước rửa chén Sunlight",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 36,
                            Barcode = "893850012003",
                            CategoryId = 12,
                            Price = 20000m,
                            ProductName = "Túi rác tự hủy",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 37,
                            Barcode = "893850013001",
                            CategoryId = 13,
                            Price = 5000m,
                            ProductName = "Bút bi Thiên Long",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 38,
                            Barcode = "893850013002",
                            CategoryId = 13,
                            Price = 25000m,
                            ProductName = "Vở Campus",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 39,
                            Barcode = "893850013003",
                            CategoryId = 13,
                            Price = 5000m,
                            ProductName = "Bút chì 2B",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 40,
                            Barcode = "893850014001",
                            CategoryId = 14,
                            Price = 12000m,
                            ProductName = "Kem Merino",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 41,
                            Barcode = "893850014002",
                            CategoryId = 14,
                            Price = 55000m,
                            ProductName = "Xúc xích đông lạnh",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 42,
                            Barcode = "893850014003",
                            CategoryId = 14,
                            Price = 45000m,
                            ProductName = "Há cảo đông lạnh",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 43,
                            Barcode = "893850015001",
                            CategoryId = 15,
                            Price = 65000m,
                            ProductName = "Táo Fuji",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 44,
                            Barcode = "893850015002",
                            CategoryId = 15,
                            Price = 30000m,
                            ProductName = "Chuối tiêu",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 45,
                            Barcode = "893850015003",
                            CategoryId = 15,
                            Price = 40000m,
                            ProductName = "Cam sành",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
